name: Angular Build Automation

on:
  push:
    branches: [ main ]

jobs:
  angular-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v7.0.0

      - name: Setup Node.js Environment
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 'v6.4.0'

      - name: Install Project Dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build
